ms-confidential:
    tenant:
        id: "f93d5f40-88c0-4650-b8f2-cc4ec3ef6a10"
    client:
        id: "c6ac7fa2-b8cc-43b2-b4df-f55854f09586"
        secret: "{9]:&n/&Q{6&o^%^&i[!)lq"
    user:
        email: "YOUR ORGANIZATION MICROSOFT-EMAIL"
        password: "YOUR MICROSOFT PASSWORD"
    grant:
        user: "password"
        application:  "client_credentials"
    scope:
        default: "https://graph.microsoft.com/.default"
